# COMMON CONFIG
COMMON_DATE_FORMAT = '%d/%m/%Y'
COMMON_DATE_PRINT_FORMAT = '%Y%m%d%H%M%S'
COMMON_DATA_SRC_CSV = 'csv'
COMMON_ALL_FILE_SELECT = '*.'
COMMON_ANALYSIS_REPORT_FILENAME = 'AnalysisReport'
COMMON_ANALYSIS_REPORT_FILE_TYPE = '.txt'

# COLUMN CONFIG
COLUMN_DATE = 'date'
COLUMN_CATEGORY = 'category'
COLUMN_AMOUNT = 'amount'

# FREQUENCY ENUM
DAILY = 1
WEEKLY = 2
MONTHLY = 3

# FREQUENCY ENUM STRING
DAILY_STR = 'DAILY'
WEEKLY_STR = 'WEEKLY'
MONTHLY_STR = 'MONTHLY'

# SUMMARY DATA PRINT MODEL
BUDGET_LIST = 'Budget List'
OVERALL_NET = 'Net Gain/Loss'
OVERALL_REMAIN = 'Remaining Balance'

# BUDGET ANALYSIS PRINT MODEL
BUDGET_NAME = 'Name'
BUDGET_ALLOCATION = 'Allocated Budget'
BUDGET_EXPECTED_EXPENSE = 'Expected Expense'
BUDGET_ACTUAL_EXPENSE = 'Actual Expense'
BUDGET_NET = 'Net Gain/Loss'
BUDGET_REMAIN = 'Remaining Balance'
BUDGET_FREQUENCY = 'Frequency'
BUDGET_SUGGESTION = 'Suggested Budget'
BUDGET_SEPARATOR = '-------------------------'