# COMMON CONFIG
COMMON_DEFAULT_BUDGET_NAME = 'new budget'
COMMON_DATE_FORMAT = '%d/%m/%Y'
COMMON_DATA_SRC_CSV = 'csv'
COMMON_ALL_FILE_SELECT = '*.'

# COLUMN CONFIG
COLUMN_DATE = 'date'
COLUMN_CATEGORY = 'category'

# CATEGORY CONFIG
CATEGORY_SALARY = 'Salary'

# FREQUENCY ENUM
DAILY = 1
WEEKLY = 2
MONTHLY = 3