# COMMON CONFIG
COMMON_DEFAULT_BUDGET_NAME = 'new budget'
COMMON_DATE_FORMAT = '%d/%m/%Y'
COMMON_DATA_SRC_CSV = 'csv'
COMMON_ALL_FILE_SELECT = '*.'

# COLUMN CONFIG
COLUMN_DATE = 'date'
COLUMN_CATEGORY = 'category'

# CATEGORY CONFIG
CATEGORY_SALARY = 'Salary'

# FREQUENCY ENUM
DAILY = 1
WEEKLY = 2
MONTHLY = 3

# SUMMARY DATA MODEL
BUDGET_LIST = 'Budget List'
OVERALL_NET = 'Net Gain/Loss'
OVERALL_REMAIN = 'Remaining Balance'
SUGGESTED_PERDAY = 'Suggested Budget per day'

# BUDGET ANALYSIS MODEL
BUDGET_NAME = 'Name'
BUDGET_ALLOCATION = 'Allocated Budget'
BUDGET_EXPECTED_EXPENSE = 'Expected Expense'
BUDGET_ACTUAL_EXPENSE = 'Actual Expense'
BUDGET_NET = 'Net Gain/Loss'
BUDGET_REMAIN = 'Remaining Balance'